"""add runbook data to incidents

Revision ID: 4fa612d881ac
Revises: a6e633306573
Create Date: 2026-04-02 01:32:19.683378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fa612d881ac'
down_revision = 'a6e633306573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('runbook_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'runbook_data')
    # ### end Alembic commands ###
