"""add prompt_runs table

Revision ID: e8662b6211cb
Revises: 96f2f9f54e14
Create Date: 2026-04-20 20:35:15.382171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8662b6211cb'
down_revision = '96f2f9f54e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('input_token_estimate', sa.Integer(), nullable=False),
    sa.Column('output_token_estimate', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_runs_created_at'), 'prompt_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_runs_incident_id'), 'prompt_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_prompt_runs_prompt_version'), 'prompt_runs', ['prompt_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_runs_prompt_version'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_incident_id'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_created_at'), table_name='prompt_runs')
    op.drop_table('prompt_runs')
    # ### end Alembic commands ###
